# Generated by Django 4.0.3 on 2022-04-30 04:14

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=400)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='img_height', null=True, upload_to='communityimages/', width_field='img_width')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('img_width', models.IntegerField(blank=True, null=True)),
                ('img_height', models.IntegerField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, height_field='img_height', null=True, upload_to='avatars/', width_field='img_width')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (100, 'Member')])),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.community')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(through='accounts.MemberRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
