# Generated by Django 4.0.3 on 2022-04-28 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='users',
            field=models.ManyToManyField(null=True, through='accounts.MemberRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
