# Generated by Django 4.0.3 on 2022-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
